spring.application.name=PassHolder
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/PassHolderDatabase
spring.datasource.username=aplikacja
spring.datasource.password=TajneHaslo21!!

